name: deploy
on:
  push:
    branches: [react-rewrite]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Vercel
        run: npx vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
